/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-central-1",
  "aws_cloud_logic_custom": [
    {
      "name": "stocker",
      "endpoint": "http://localhost:3001",
      "region": "eu-central-1"
    }
  ]
};


export default awsmobile;
