name: Staging sync
on:
  push:
    branches:
      - master
      - fix_branch_sync_v2
  workflow_dispatch:

jobs:
  sync-branches:
    name: Staging sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Syncing branches
        id: pull
        uses: tretuna/sync-branches@main
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "staging"
          # PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
